'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { HypeCheckReport } from '@/lib/types'
import ReportHeader from '@/components/report/ReportHeader'
import MarketOpportunity from '@/components/report/MarketOpportunity'
import CompetitiveLandscape from '@/components/report/CompetitiveLandscape'
import DemandSignals from '@/components/report/DemandSignals'
import MonetisationViability from '@/components/report/MonetisationViability'
import ExecutionRisk from '@/components/report/ExecutionRisk'
import NextStep from '@/components/report/NextStep'

export default function ReportPage() {
  const [report, setReport] = useState<HypeCheckReport | null>(null)
  const router = useRouter()

  useEffect(() => {
    const stored = sessionStorage.getItem('hypecheckReport')
    if (!stored) {
      router.push('/check')
      return
    }
    try {
      setReport(JSON.parse(stored))
    } catch {
      router.push('/check')
    }
  }, [router])

  if (!report) {
    return (
      <main className="min-h-screen bg-[#0A0A0A] flex items-center justify-center">
        <div className="flex flex-col items-center gap-4">
          <div className="h-8 w-8 animate-spin rounded-full border-2 border-[#2A2A2A] border-t-[#7C3AED]" />
          <p className="text-[13px] text-[#555555]">Loading your report...</p>
        </div>
      </main>
    )
  }

  return (
    <main className="min-h-screen bg-[#0A0A0A] px-4 py-12">
      <div className="mx-auto flex max-w-[720px] flex-col gap-4">

        {/* Back link */}
        <button
          onClick={() => router.push('/check')}
          className="self-start text-[13px] text-[#555555] hover:text-[#F5F5F5] transition-colors mb-2"
        >
          ← Check another idea
        </button>

        <ReportHeader
          ideaTitle={report.ideaTitle}
          hypeScore={report.hypeScore}
          verdict={report.verdict}
          oneLinerSummary={report.oneLinerSummary}
        />
        <MarketOpportunity
          metrics={report.marketOpportunity.metrics}
        />
        <CompetitiveLandscape
          competitors={report.competitiveLandscape.competitors}
          competitiveAdvantage={report.competitiveLandscape.competitiveAdvantage}
        />
        <DemandSignals
          signals={report.demandSignals.signals}
          overallDemandStrength={report.demandSignals.overallDemandStrength}
        />
        <MonetisationViability
          score={report.monetisationViability.score}
          recommendedModel={report.monetisationViability.recommendedModel}
          pricingSuggestion={report.monetisationViability.pricingSuggestion}
          keyRisk={report.monetisationViability.keyRisk}
        />
        <ExecutionRisk
          factors={report.executionRisk.factors}
          overallRiskLevel={report.executionRisk.overallRiskLevel}
        />
        <NextStep
          action={report.nextStep.action}
          rationale={report.nextStep.rationale}
        />

        {/* Footer */}
        <p className="pb-8 pt-4 text-center text-[12px] text-[#555555]">
          Generated by{' '}
          <span className="text-[#7C3AED]">HypeCheck</span> · NullHype AI
        </p>
      </div>
    </main>
  )
}
