import { HypeCheckReport } from '@/lib/types'
import ReportHeader from './ReportHeader'
import MarketOpportunity from './MarketOpportunity'
import CompetitiveLandscape from './CompetitiveLandscape'
import DemandSignals from './DemandSignals'
import MonetisationViability from './MonetisationViability'
import ExecutionRisk from './ExecutionRisk'
import NextStep from './NextStep'
import { sanitizeReportText } from '@/lib/sanitizeText'

export default function ReportView({ report }: { report: HypeCheckReport }) {
  const cleanReport = sanitizeReportText(report)

  return (
    <>
      <ReportHeader
        ideaTitle={cleanReport.ideaTitle}
        hypeScore={cleanReport.hypeScore}
        verdict={cleanReport.verdict}
        oneLinerSummary={cleanReport.oneLinerSummary}
      />
      <MarketOpportunity
        metrics={cleanReport.marketOpportunity.metrics}
      />
      <CompetitiveLandscape
        competitors={cleanReport.competitiveLandscape.competitors}
        competitiveAdvantage={cleanReport.competitiveLandscape.competitiveAdvantage}
      />
      <DemandSignals
        signals={cleanReport.demandSignals.signals}
        overallDemandStrength={cleanReport.demandSignals.overallDemandStrength}
      />
      <MonetisationViability
        score={cleanReport.monetisationViability.score}
        recommendedModel={cleanReport.monetisationViability.recommendedModel}
        pricingSuggestion={cleanReport.monetisationViability.pricingSuggestion}
        keyRisk={cleanReport.monetisationViability.keyRisk}
      />
      <ExecutionRisk
        factors={cleanReport.executionRisk.factors}
        overallRiskLevel={cleanReport.executionRisk.overallRiskLevel}
      />
      <NextStep
        action={cleanReport.nextStep.action}
        rationale={cleanReport.nextStep.rationale}
      />
      <p className="pb-8 pt-4 text-center text-[12px] text-[#555555]">
        Generated by{' '}
        <span className="text-[#2563EB]">HypeCheck</span> · NullHype AI
      </p>
    </>
  )
}
