import Link from "next/link";

export const metadata = {
  title: "Terms of Service - HypeCheck",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0A0A0A] px-4 py-16">
      <div className="mx-auto max-w-2xl">
        <Link
          href="/"
          className="text-[13px] text-[#555555] hover:text-[#999999] transition-colors"
        >
          ← Back to home
        </Link>

        <h1 className="mt-8 text-3xl font-bold text-[#F5F5F5]">Terms of Service</h1>
        <p className="mt-2 text-[13px] text-[#555555]">Last updated: May 2026</p>

        <div className="mt-10 space-y-8 text-[15px] leading-relaxed text-[#999999]">
          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#F5F5F5]">The service</h2>
            <p>
              HypeCheck is an AI powered startup idea validation tool operated by NullHype AI.
              You describe a startup or side project idea and receive a structured analysis
              report including a viability score, competitor landscape, market sizing, and
              a build recommendation.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#F5F5F5]">Accounts</h2>
            <p>
              You sign in using Google or GitHub OAuth. You are responsible for maintaining
              access to your OAuth account. One account per person. Do not create multiple
              accounts to abuse the free tier.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#F5F5F5]">Free tier and payments</h2>
            <p>
              Every account receives 3 free reports. Additional reports can be purchased
              as one-time payments. There are no subscriptions or recurring charges. Payments
              are processed by Dodo Payments. All purchases are final and non-refundable,
              as the AI analysis is delivered immediately upon purchase. If you experience a
              technical issue that prevents report delivery, contact us for a resolution.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#F5F5F5]">Report credits</h2>
            <p>
              Purchased report credits do not expire. Credits are tied to your account and
              are not transferable. Each report generation consumes one credit.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#F5F5F5]">AI generated content</h2>
            <p>
              Reports are generated by AI (Anthropic Claude) and are provided for informational
              purposes only. HypeCheck does not guarantee the accuracy, completeness, or
              reliability of any analysis. Reports should not be treated as professional
              business, legal, or financial advice. You are solely responsible for any
              decisions you make based on a HypeCheck report.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#F5F5F5]">Your content</h2>
            <p>
              You retain ownership of the idea text you submit. By using HypeCheck, you grant
              us a limited licence to process your text through the AI in order to generate
              your report. We do not claim ownership of your ideas or reports. We do not share
              your idea text with anyone other than the AI provider (Anthropic) for the purpose
              of generating your report.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#F5F5F5]">Shareable reports</h2>
            <p>
              When you share a report link, anyone with that link can view the full report
              including the idea description and analysis. Sharing is your choice. We do not
              publish or distribute your reports without your action.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#F5F5F5]">Acceptable use</h2>
            <p>
              Do not use HypeCheck to generate reports for illegal activities, to spam the
              service with automated requests, or to attempt to extract or reverse engineer
              the AI prompts. We reserve the right to suspend accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#F5F5F5]">Limitation of liability</h2>
            <p>
              HypeCheck is provided as is without warranties of any kind. NullHype AI is not
              liable for any damages arising from your use of the service, reliance on AI
              generated reports, or any business decisions influenced by the analysis.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#F5F5F5]">Changes to these terms</h2>
            <p>
              We may update these terms from time to time. If we make material changes, we will
              update the date at the top of this page. Continued use of HypeCheck after changes
              constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#F5F5F5]">Contact</h2>
            <p>
              Questions about these terms? Email us at{" "}
              <a
                href="mailto:hello@nullhype.tech"
                className="text-[#60A5FA] hover:text-[#93C5FD] underline underline-offset-2"
              >
                hello@nullhype.tech
              </a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
